# TODO: better compose our compose files so that this isn't just in the override file
services:
  kafkaconsumer:
    container_name: kafkaconsumer
    build:
      context: .
      dockerfile: KafkaConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5054:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  kafkaproducer:
    container_name: kafkaproducer
    build:
      context: .
      dockerfile: KafkaProducer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5295:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
