services:
  schemamanager:
    container_name: schemamanager
    build:
      context: .
      dockerfile: SchemaManager/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Kafka__BootstrapServers=broker:29092
      - Kafka__SchemaRegistryUrl=http://schema-registry:8081
    depends_on:
      schema-registry:
        condition: service_started
    restart: "no"

  kafkaconsumer:
    container_name: kafkaconsumer
    build:
      context: .
      dockerfile: KafkaConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - Kafka__BootstrapServers=broker:29092
      - Kafka__SchemaRegistryUrl=http://schema-registry:8081
      - GROUP_ID=test-1
    ports:
      - "5054:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      schemamanager:
        condition: service_completed_successfully

  kafkaproducer:
    container_name: kafkaproducer
    build:
      context: .
      dockerfile: KafkaProducer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - Kafka__BootstrapServers=broker:29092
      - Kafka__SchemaRegistryUrl=http://schema-registry:8081
    ports:
      - "5295:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      schemamanager:
        condition: service_completed_successfully
