services:
  schema-register:
    container_name: schema-register
    build:
      context: .
      dockerfile: Schemas/SchemaRegister/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Kafka__BootstrapServers=broker:29092
      - Kafka__SchemaRegistryUrl=http://schema-registry:8081
    depends_on:
      schema-registry:
        condition: service_started
    restart: "no"

  order-consumer:
    container_name: order-consumer
    build:
      context: .
      dockerfile: OrderConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - Kafka__BootstrapServers=broker:29092
      - Kafka__SchemaRegistryUrl=http://schema-registry:8081
      - GROUP_ID=test-1
    ports:
      - "5054:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      schema-register:
        condition: service_completed_successfully

  order-producer:
    container_name: order-producer
    build:
      context: .
      dockerfile: OrderProducer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - Kafka__BootstrapServers=broker:29092
      - Kafka__SchemaRegistryUrl=http://schema-registry:8081
    ports:
      - "5295:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      schema-register:
        condition: service_completed_successfully
